services:
  mysql:
    image: mysql
    container_name: grfblog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grfblog
      MYSQL_USER: grfblog
      MYSQL_PASSWORD: grfblog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
